config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :kids
  resources :rewards
  resources :games, only: [:index, :show] do
    resources :reservations, only: [:new, :create] do
      patch :greenstarscounter
      put :greenstarscounter
    end

  end
  resources :reservations, only: [:update] do
    resources :comments, only: :create
  end
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

end

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">

    <!-- to do add more pics in carousel-->

  </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

app/views/shared/_favourite_card.html.erb
<%# if user_signed_in? %>
  <%# @all_reservations = current_user.reservations.where(kindergarden: kindergarden) %>
  <%# @declined_reservations = current_user.reservations.where(kindergarden: kindergarden, status: 'Declined') %>
<%# end %>

<div class="card">
  <% if game.photo.present? %>
    <div class="card-img" style="background-image: url('<%= cl_image_path kindergarden.photo, height: 300, width: 400, crop: :fill %>')"></div>
  <% else %>
    <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))"></div>
  <%end%>
  <div class="card-description">
    <span><%= link_to game.name, game_path(game)%></span>

    <p><%= kindergarden.description %></p>
    <div>
      <%=link_to "More details", game_path(game.id) %>
      <% if game.is_available == true %>
        <% if user_signed_in? %>
          <% if current_user.kids.exists? %>
            <% if !@declined_reservations.empty? || @all_reservations.empty? %>
              <%= link_to "Select", new_game_reservation_path(game) %>
            <% end %>
          <% else %>
            <%= link_to "Add your kid first", new_kid_path %>
          <% end %>
        <% else %>
          <%=link_to "Select", new_game_reservation_path(game) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small stylish-color-dark pt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Happy Kid</h5>
        <p>48 Damerow Strasse<br> 13187 Berlin<br> Deutschland <br>+49 030 12345678</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Resources</h5>

        <ul class="list-unstyled">
          <li>
            <a href="http://www.berlinforallthefamily.com/childcare--schools/how-to-apply-for-a-kita-spot-in-berlin-kita-gutschein-waiting-lists-fees-explained">Application process</a>
          </li>
          <li>
            <a href="https://www.berlin.de/sen/jugend/familie-und-kinder/kindertagesbetreuung/kitas/">Official documents</a>
          </li>
          <li>
            <a href="https://www.howtogermany.com/pages/kindergeld.html">Children's allowance</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Documents</h5>

        <ul class="list-unstyled">
          <li>
             <a href="https://www.berlin.de/ba-marzahn-hellersdorf/service/dienstleistungen/service.30747.php/dienstleistung/324873/standort/123597/pdf/">Kita Gutschein</a>
          </li>
          <li>
            <a href="https://www.kindergeld.org/download/KG1.pdf">Kindergeld</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center pb-4">
    <ul class="list-inline social-buttons">
      <li class="list-inline-item">
        <a href="#">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="#">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
      <li class="list-inline-item">
        <a href="#">
          <i class="fab fa-instagram"></i>
        </a>
      </li>
    </ul>
  </ul>
  <!-- Social buttons -->

</footer>
<!-- Footer -->

app/views/shared/_kita_card.html.erb
<% if user_signed_in? %>

<% end %>

<div class="card <%= 'card-index' if controller_name == 'games' && action_name == 'index' %>">
  <% if game.photo.present? %>
    <div class="card-img" style="background-image: url('<%= image_path game.photo, height: 300, width: 400, crop: :fill %>')"></div>
  <% else %>
    <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))"></div>
  <%end%>
  <div class="card-description">
    <h2><%=game.name%></h2>


    <p style="color: rgba(0,0,0,0.6);"><%= truncate(game.description, length: 100, separator: ' ') %></p>
    <div class="d-flex justify-content-between">
      <%=link_to "More details", game_path(game.id), class: "btn btn-secondary" %>

      <!-- insertion from show -->



      <!-- insertion from show -->



    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-application navbar-expand-sm">
  <div class="container">
    <%= link_to "#", class: "navbar-brand" do %>

    <% end %>



      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= controller_name == "pages" && action_name == "home" ? "active" : ""%>">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= controller_name == "pages" && action_name == "dashboard" ? "active" : ""%>">
          <%= link_to "My Board", dashboard_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dsu1ribvb/image/upload/v1588075610/user_hau5oh.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <!-- to do = change user avatar -->
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/shared/_navbar_home.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <%= link_to "#", class: "navbar-brand" do %>

    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item <%= controller_name == "pages" && action_name == "home" ? "active" : ""%>">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= controller_name == "pages" && action_name == "dashboard" ? "active" : ""%>">
            <%= link_to "My Board", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= controller_name == "pages" && action_name == "messages" ? "active" : ""%>">
            <%= link_to "", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dsu1ribvb/image/upload/v1588075610/user_hau5oh.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- END nav -->