config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :kids
  resources :rewards
  resources :games, only: [:index, :show] do
    resources :reservations, only: [:new, :create] do
      patch :greenstarscounter
      put :greenstarscounter
    end

  end
  resources :reservations, only: [:update] do
    resources :comments, only: :create
  end
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

end

app/views/pages/_advancedsearch.html.erb
<%= form_tag games_path, method: :get, class: "search-location mt-md-5" do %>

      <div class="form-group">
        <div class="form-field">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by name of area of behaviour",
            autocomplete: "off"
            %>
            <div class="d-flex filters">

            <!-- old search by label tag -->

            </div>
            <button ><span class="ion-ios-search"><i class="fas fa-search"></i></span></button>

            <% end %>
        </div>
      </div>

app/views/pages/_wheel.html.erb
<!-- <link href='https://fonts.googleapis.com/css?family=Exo+2:900' rel='stylesheet' type='text/css'> -->

<div id="wrapper">

        <div id="wheel">
            <div id="inner-wheel">
                <% current_user.rewards.each do |reward| %>
                  <div class="sec"><span class="fa text"><%= reward.first_prize %></span></div>
                  <div class="sec"><span class="fa text"><%= reward.second_prize %></span></div>
                  <div class="sec"><span class="fa text"><%= reward.third_prize %></span></div>
                  <div class="sec"><span class="fa text"><%= reward.fourth_prize %></span></div>
                  <div class="sec"><span class="fa text"><%= reward.fifth_prize %></span></div>
                <% end %>
                <div class="sec"><span class="fa fa-gift"></span></div>
            </div>

            <div id="spin">
                <div id="inner-spin"></div>
            </div>

            <div id="shine"></div>
        </div>


        <div id="txt"></div>
  </div>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="js/index.js"></script>




  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <div class="container dashboard-section" id="all-kindergardens" style="margin-bottom: 30px;">
    <div class="section-title" style=" color: #f57170;">
      <h4>My Games</h4>
    </div>
    <table style="width: 100%;">
      <thead>
        <tr>

          <th class="table-dashboard" style="padding: 8px;">Child</th>
          <th class="table-dashboard" style="padding: 8px;">Areas</th>
          <th class="table-dashboard" style="padding: 8px;">Mon</th>
          <th class="table-dashboard" style="padding: 8px;">Tue</th>
          <th class="table-dashboard" style="padding: 8px;">Wed</th>
          <th class="table-dashboard" style="padding: 8px;">Thu</th>
          <th class="table-dashboard" style="padding: 8px;">Fri</th>
          <th class="table-dashboard" style="padding: 8px;">Sat</th>
          <th class="table-dashboard" style="padding: 8px;">Sun</th>
          <th class="table-dashboard" style="padding: 8px; color:black">Stars <i class="fas fa-star fa-lg" style="color:yellow;"></i></th>




        </tr>
      </thead>
      <tbody class="dashboard-table">
        <% @kids.each do |kid| %>
          <% if kid.reservations.exists? %>
            <tr>
              <td class="table-dashboard">
                <%= kid.first_name  %>
              </td>
              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">
                    <%= reservation.game.name %>
                  </div>
                <% end %>
              </td>


              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">


                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                 </div>
                <% end %>
              </td>


              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                  </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                  </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                   </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                  </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                   </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">

                    <%= link_to "Add Stars", game_path(reservation.game), class: "btn btn-addstar" %>
                   </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>

                  <div class="table-item">
                    You have
                    <% if reservation.stars? %>
                        <strong> <%= reservation.stars %> </strong>
                    <% else %>
                      0
                    <% end %>
                    Stars
                  </div>
                <% end %>
              </td>






            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="container dashboard-section" id="my-kids">
    <div class="section-title" style=" margin-top: 15px; color: #f57170;">
      <h4>My Kids</h4>
    </div>
    <div class="row kid-сards">
      <% current_user.kids.each do |kid| %>
        <div class="col-3 kid-card">
          <%= link_to edit_kid_path(kid) do %>
            <span><%= kid.first_name %></span>
          <% end %>
        </div>
      <% end %>

      <div class="col-3 kid-card kid-card-add">
        <%= link_to new_kid_path(current_user) do %>
          <span>Add kid <i class="far fa-plus-square"></i></span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container dashboard-section" id="my-kids">
    <div class="section-title" style=" margin-top: 15px; color: #f57170;">
      <h4>My Rewards</h4>
    </div>
    <div class="row kid-сards">
      <% current_user.rewards.each do |reward| %>
        <div class="col-3 kid-card">
          <%= link_to edit_reward_path(reward) do %>
            <span><%= reward.name %></span>
          <% end %>
        </div>
      <% end %>

      <div class="col-3 kid-card kid-card-add">
        <%= link_to new_reward_path(current_user) do %>
          <span>Add reward <i class="far fa-plus-square"></i></span>
        <% end %>
      </div>
    </div>
  </div>




  </div>
</div>
<%= render "shared/footer", game: @game %>

app/views/pages/home.html.erb
<html>
  <head>
    <title>Happy Kid</title>
    <meta name="description" content="Happy Kid helps you and your kid to grow up correcting bad habits into good ones!">
    <meta charset="utf-8">
    <meta property="og:title" content="Happy Kid - Rewards your kid's progresses!">
    <meta property="og:image" content="happykid.jpeg">
    <meta property="og:description" content="Happy Kid helps you and your kid to grow up correcting bad habits into good ones!">
    <meta property="og:site_name" content="Happy Kid">
  </head>
  <body>
    <div class='bg'></div>
    <div class="jumbotron paral paralsec">

      <div class="container">
        <div class="row no-gutters slider-text justify-content-center align-items-center">
          <div class="col-lg-8 col-md-6 d-flex justify-content-center align-items-end">
            <div class="text text-center">
              <h1 class="main-title">.........................</h1>
              <p style="font-size: 18px;">I reward your kid turning bad habits into good ones.</p>
                <div>
                  <%= form_tag games_path, method: :get, class: "search-location mt-md-5" do %>
                      <div class="row justify-content-center">
                        <div class="col-lg-10 align-items-end">
                          <div class="form-group">
                            <div class="form-field">
                              <%= text_field_tag :query,
                                params[:query],
                                class: "form-control",
                                placeholder: "Search by area of the problem.",
                                autocomplete: "off"
                                %>
                              <button ><span class="ion-ios-search"><i class="fas fa-search"></i></span></button>
                            </div>
                          </div>
                        </div>
                      </div>
              <% end %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="overlay">
    <a href="#apply">
      <div class="arrow">
        <i class="fas fa-long-arrow-alt-down"></i>
      </div>
      </a>
    </div>

    <section class="content-section" id="apply">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">The simplest way to reward your kid</h2>
            <h3 class="section-subheading text-muted">We help your kid in a playful way, track his progress on your dashboard!</h3>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-3">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-search-location fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">1. Select</h4>
            <p class="text-muted">Select the areas you feel your kid needs help with. </p>
          </div>
          <div class="col-md-3">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-file-alt fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">2. Set</h4>
            <p class="text-muted">Set daily and monthly targets according to your kid's needs.</p>
          </div>
          <div class="col-md-3">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-baby fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">3. Track</h4>
            <p class="text-muted">Track his behaviours and match the targets.</p>
          </div>
            <div class="col-md-3">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-child fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">4. Get rewards</h4>
            <p class="text-muted">Congratulations! You met your targets, spin the wheel and get the rewards you deserve! </p>
          </div>
        </div>
      </div>
    </section>
    to do <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/week.html.erb
<div class="container">

  <div class="container dashboard-section" id="all-kindergardens" style="margin-bottom: 30px;">
    <div class="section-title" style=" color: #f57170;">
      <h4>My Week</h4>
    </div>
    <table style="width: 100%;">
      <thead>
        <tr>

          <th class="table-dashboard" style="padding: 8px;">Area</th>
          <th class="table-dashboard" style="padding: 8px;">Monday</th>
          <th class="table-dashboard" style="padding: 8px;">Tuesday</th>
          <th class="table-dashboard" style="padding: 8px;">Wednesday</th>
          <th class="table-dashboard" style="padding: 8px;">Thursday</th>
          <th class="table-dashboard" style="padding: 8px;">Friday</th>
          <th class="table-dashboard" style="padding: 8px;">Saturday</th>
          <th class="table-dashboard" style="padding: 8px;">Sunday</th>



        </tr>
      </thead>
      <tbody class="dashboard-table">
        <% @kids.each do |kid| %>
          <% if kid.reservations.exists? %>
            <tr>
              <td class="table-dashboard">
                <%= reservation.game.name  %>
              </td>


              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">
                    <%= reservation.green_stars %>
                  </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">
                    <%= reservation.yellow_stars %>
                  </div>
                <% end %>
              </td>

              <td class="table-dashboard">
                <% kid.reservations.each do |reservation| %>
                  <div class="table-item">
                    <%= reservation.red_stars %>
                  </div>
                <% end %>
              </td>


                        <!-- link_to "Spin the Wheel!", "pages/wheel" -->



            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>


</div>
<%= render "shared/footer", game: @game %>